update uninstall script

diff --git a/uninstall b/uninstall
--- a/uninstall
+++ b/uninstall
@@ -17,23 +17,24 @@ declare root="$(dirname "$0")/$1"
 [ ! -d "$root" ] && echo "Parent folder does not exist." && exit 1
 
 # Stow a file in the target directory
-create_symlink() {
+delete_symlink() {
   local folder=${1:-NULL}
-  [ -z $folder ] && echo "Invalid folder path." && return
+  [ -z $folder ] && echo "Invalid folder path." && return 1
   local foldername=$(basename $folder)
 
   echo "Removing symlink for ${foldername}.."
   # delete if a symlink already exist
   stow --target=$target --dir=$root -D $foldername
-  [ $? -ne 0 ] && echo "Failed." && return
+  [ $? -ne 0 ] && echo "Failed." && return 1
+  return 0
 }
 
 
-# Create a bunch of symlinks
+# Delete all the symlinks
 echo "Target location: ${target}"
 
 for folder in $(ls -d -- $root/*)
 do
-  create_symlink $folder
+  delete_symlink $folder
 done
 
